services:
  movie-app-api:
    image: movie-app-api:latest
    container_name: movie-app
    depends_on:
      - db
      - movie-app-fe
    environment:
      - DB_URL=jdbc:postgresql://db:5432/movie_app_api
      - DB_USERNAME=developer
      - DB_PASSWORD=123456
    ports:
      - 8080:8080
  db:
    image: postgres:16
    container_name: movieappdb
    environment:
      - POSTGRES_DB=movie_app_api
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=developer
    ports:
      - 8000:5432